### ISSUE TITLE
Not compatible with ovos_utils v0.12a1

### ISSUE THREAD

**Issue by theCalcaholic** [JarbasSkills/skill-sovietwave#2]
Apparently, there is no module ovos_utils.skills.templates in the latest release of ovos_utils.
See also https://github.com/JarbasSkills/skill-old-world-radio/issues/2

Stack Trace:

```
Failed to load skill: skill-sovietwave.jarbasskills (ModuleNotFoundError("No module named 'ovos_utils.skills.templates'"))
Traceback (most recent call last):
  File "/home/neon/bigscreen-build/mycroft-core/mycroft/skills/skill_loader.py", line 276, in _load_skill_source
    skill_module = load_skill_module(main_file_path, self.skill_id)
  File "/home/neon/bigscreen-build/mycroft-core/mycroft/skills/skill_loader.py", line 72, in load_skill_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/skill-sovietwave.jarbasskills/__init__.py", line 3, in <module>
    from ovos_utils.skills.templates.video_collection import VideoCollectionSkill
```

**Comment by JarbasAl** [comment]
this functionality has been migrated from ovos_utils to https://github.com/OpenVoiceOS/OVOS-workshop

**Comment by theCalcaholic** [comment]
I see. Is this already supposed to be reflected in the skill? Can I update to another branch/version or something like that?

**Comment by JarbasAl** [comment]
no, this needs to be fixed, currently the skill is incompatible with latest ovos_utils version

the whole ovos-common-play framework is currently in a state of flux due to mycroft team not wanting to use it and going their own way, skills need constant updates.

The mycroft implementation is also work in progress and changing, so any change they make might break compatibility at any time (official skills stop working, not ovos-common-play skills)

Still trying to figure out the best way to integrate both approaches, currently using the ovos version of common play requires blacklisting the mycroft version and backwards compatibility is not ensured, apologies for the bumpy road.

the OVOS team will be doing a sprint for this soon and i will be reviewing existing skills.

**Comment by JarbasAl** [comment]
that said if you want to just edit the imports it might just work out of the box! i will give that a try later today or tomorrow, stay tuned

**Comment by JarbasAl** [comment]
seems the update was easier than expected, latest version should be working, please open new issues if come across any new problem

old world radio imports have also been updated, but as i said in that issue the streams went down and need to be replaced, so that one will take a little longer to get back up and running

**Comment by theCalcaholic** [comment]
Thank you! :)

So... I hope you forgive my for misusing this issue for a different topic, but I was wondering how plasma bigscreen, OVOS and whatever runs on the official devices from mycroft.ai are related?
Is OVOS basically a community project that strives to be something similar to what mycroft.ai does, but under the control of an open source community?

I've just recently gotten back into tinkering with mycroft, because I came across plasma bigscreen and decided to try and set it up myself (not on a rp4 though, so it took a bit of research and experimentation :smiley:  ), so I missed most of the developments of the last 1-2 years.

Since I remember you as pretty much being the soul of the community (at least the tinkering part), I'd be very much interested in your opinion of that.

**Comment by JarbasAl** [comment]
ha, i thought your username was familiar, nice to see you getting back!

for OVOS questions we now have a discussions board https://github.com/OpenVoiceOS/OpenVoiceOS/discussions

Your assessment is correct, OVOS is meant to be fully community controlled, at this point in time the mycroft team is small and focused on the mark2, you measure the time PRs stay unreviewed and unmerged in months/years. If we can't work in mycroft-core we will still work somewhere.... OVOS wasn't planned, it just formed naturally in the mattermost chat from community members, all the tools we create should work in regular mycroft-core and any other derivative projects

**Comment by theCalcaholic** [comment]
Cool, thank you for the insights :)
